### ISSUE TITLE
[Security Self-Assessment] Jaeger

### ISSUE THREAD

**Issue by jw6680** [Rana-KV/tag-security#1]
### Details
Project Name: Jaeger

Github URL: https://github.com/jaegertracing/jaeger

CNCF project stage: Sandbox preparing for Incubation / Incubation preparing for Graduation / Graduated
- Graduation Proposal: https://github.com/jaegertracing/jaeger

Security Provider: No

Self-assessment link (before PR): [Jaeger Security Self-Assessment](https://github.com/cp-57/tag-security/blob/main/assessments/projects/jaeger/self-assessment.md)

### Tasks
- [x] Stage 1: Preparation
   - [x] Create a GitHub issue for the security self assessment of Jaeger project.
      - [x] Issue Link in CNCF Tag-Security: https://github.com/Rana-KV/tag-security/issues/1
   - [x] Create a place holder of security self assessment.
      - [x] Create a fork of the CNCF Tag-Security in your Github.
      - [x] Create a new folder for the Jaeger project.
      - [x] Add the security self assessment template under the project folder.
      - [x] Issue link of Initial Commit: https://github.com/cp-57/tag-security/commit/5ea77286705c1537774244a8488a30dd887991b2
   - [x] Review Documentation of the Jaeger project.
- [x]  Stage 2: Understand the Project Landscape
   - [x] Understand the overall project at a sufficient level of detail.
   - [x] Update overview section
      - [x] **Background** <br> commit: https://github.com/cp-57/tag-security/commit/0f3c4206eccd97077ebb81a32238b745ac13675d
      - [x] **Actors** <br> commit: https://github.com/cp-57/tag-security/commit/0f3c4206eccd97077ebb81a32238b745ac13675d
      - [x] **Actions** <br> commit: https://github.com/cp-57/tag-security/commit/0f3c4206eccd97077ebb81a32238b745ac13675d
      - [x] **Goals** <br> commit: https://github.com/cp-57/tag-security/commit/0f3c4206eccd97077ebb81a32238b745ac13675d
      - [x] **Non-Goals** <br> commit: https://github.com/cp-57/tag-security/commit/0f3c4206eccd97077ebb81a32238b745ac13675d
- [x]  Stage 3: First complete draft of the Self Assessment
   - [x] Document technical specifications of the Jaeger project.
      - [x] **Self assessment use** <br> commit: https://github.com/cp-57/tag-security/commit/0f3c4206eccd97077ebb81a32238b745ac13675d
      - [x] **Security functions and features** <br> commit: https://github.com/cp-57/tag-security/commit/0f3c4206eccd97077ebb81a32238b745ac13675d
      - [x] **Project compliance** <br> commit: https://github.com/cp-57/tag-security/commit/0f3c4206eccd97077ebb81a32238b745ac13675d
      - [x] **Secure development practices** <br> commit: https://github.com/cp-57/tag-security/commit/0f3c4206eccd97077ebb81a32238b745ac13675d
      - [x] **Security issue resolution** <br> commit: https://github.com/cp-57/tag-security/commit/0f3c4206eccd97077ebb81a32238b745ac13675d
      - [x] **Appendix** <br> commit: https://github.com/cp-57/tag-security/commit/0f3c4206eccd97077ebb81a32238b745ac13675d
   - [x] Complete the security self assessment draft.

- [x]  Stage 4: Iteration with the project
   - [x] Initiate discussion with Jaeger project maintainers.
   - [x] Incorporate inputs and feedback from Jaeger project maintainers.
   - [x] Document the findings.

- [ ] Stage 5: Finalization
   - [x] Initiate PR
   - [x] Get feedback and findings from reviewers
   - [x] Fix the findings
   - [ ] Merge the PR
   - [ ] Close the issue
