### ISSUE TITLE
[Security Self Assessment] Contour

### ISSUE THREAD

**Issue by jriv01** [Rana-KV/tag-security#10]
### Details
Project Name: Contour

Github URL: https://github.com/projectcontour/contour 

CNCF project stage: Incubation preparing for graduation
- [Incubation Proposal](https://github.com/cncf/toc/blob/fbc846a3ac3f58ee9fe25d722cc64f0bf15bd86c/proposals/incubation/contour.adoc)

Security Provider: No

Self-assessment link (before PR): [Contour Security Self-Assessment](https://github.com/jriv01/tag-security/blob/main/assessments/projects/contour/self-assessment.md)

### Tasks
- [x] Stage 1: Preparation
   - [x] Create a GitHub issue for the security self assessment of Contour project.
      - [x] Issue Link in CNCF Tag-Security:  #10
   - [x] Create a place holder of security self assessment.
      - [x] Create a fork of the CNCF Tag-Security in your Github.
      - [x] Create a new folder for the Contour project.
      - [x] Add the security self assessment template under the project folder.
      - [x] Issue link of Initial Commit: c56cb2dd79587b03f7dd311a04c787b07473f091
   - [x] Review Documentation of the Contour project.
- [x]  Stage 2: Understand the Project Landscape
   - [x] Understand the overall project at a sufficient level of detail.
   - [x] Update overview section
      - [x] **Background** <br> commit: 0c3ae33059d5086befbb57130b601bae8fdfae15
      - [x] **Actors** <br> commit: 6be07a15f0d90c37cd5ae709474540fc6ad4ff13
      - [x] **Actions** <br> commit: 0b47df039389fa9e7c27e57dd8ccb45435bb0228
      - [x] **Goals** <br> commit: 5d90f113287222a128ff8e52dc8ec747e8506312
      - [x] **Non-Goals** <br> commit: e2ac6675521db478b94d953da94ba415371bb680
- [x]  Stage 3: First complete draft of the Self Assessment
   - [x] Document technical specifications of the <project_name> project.
      - [x] **Self assessment use** <br> commit: 2b389f9bb1ae70fcd5cef426ee34d303601b637a
      - [x] **Security functions and features** <br> commit: 2b389f9bb1ae70fcd5cef426ee34d303601b637a
      - [x] **Project compliance** <br> commit: 2b389f9bb1ae70fcd5cef426ee34d303601b637a
      - [x] **Secure development practices** <br> commit: 2b389f9bb1ae70fcd5cef426ee34d303601b637a
      - [x] **Security issue resolution** <br> commit: 4374eb39a6dca64bdc23b0666335f8b7a39fe95a
      - [x] **Appendix** <br> commit: 78ccd0b8295341d8ffab317acd403f5eb4467b2d
   - [x] Complete the security self assessment draft.

- [ ]  Stage 4: Iteration with the project
   - [ ] Initiate discussion with Contour project maintainers.
   - [ ] Incorporate inputs and feedback from Contour project maintainers.
   - [ ] Document the findings.

- [ ] Stage 5: Finalization
   - [ ] Initiate PR
   - [ ] Get feedback and findings from reviewers
   - [ ] Fix the findings
   - [ ] Merge the PR
   - [ ] Close the issue
