### ISSUE TITLE
[Security Self Assessment] Fluentd

### ISSUE THREAD

**Issue by Nihal-Rahman** [Rana-KV/tag-security#11]
### Details
Project Name: Fluentd

Github URL: https://github.com/fluent/fluentd

CNCF project stage: Graduated
- Graduation Proposal: https://github.com/fluent/fluentd/pull/1321

Security Provider: No

Self-assessment link (before PR): [Fluent Security Self-Assessment](https://github.com/Nihal-Rahman/tag-security/blob/main/assessments/projects/fluentd/self-assessment.md)

### Tasks
- [x] Stage 1: Preparation
   - [x] Create a GitHub issue for the security self assessment of Fluentd project.
       - [x]  Issue Link in CNCF Tag-Security: https://github.com/Rana-KV/tag-security/issues/11
   - [x] Create a place holder of security self assessment.
       - [x]  Create a fork of the CNCF Tag-Security in your Github.
       - [x] Create a new folder for the Fluentd project.
       - [x] Add the security self assessment template under the project folder.
       - [x]  Issue link of Initial Commit: [ca48adb](https://github.com/Rana-KV/tag-security/commit/ca48adb75efd5b64c91119a3cc05dadae616bbad)
    - [x] Review Documentation of the Fluentd project.

- [x]  Stage 2: Understand the Project Landscape
   - [x] Understand the overall project at a sufficient level of detail.
   - [x]  Update overview section
       - [x]  Background
                commit: [d62eadd](https://github.com/Rana-KV/tag-security/commit/d62eadd3215f18a35792e91f11a3cdd5ce57b636)
       - [x] Actors
              commit: [ba00329](https://github.com/Rana-KV/tag-security/commit/ba00329a1e2f02dfdee31dfa19519182e665e1c5)
       - [x] Actions
              commit: [1bd2e33](https://github.com/Rana-KV/tag-security/commit/1bd2e33fc0879f35ab84006f168a08b799257050)
       - [x] Goals
              commit: [8332bd4](https://github.com/Rana-KV/tag-security/commit/8332bd4e5e8cbe6d772356527305af194d816957)
       - [x] Non-Goals
              commit: [cfacad7](https://github.com/Rana-KV/tag-security/commit/cfacad705191a8cf7705475073c576ea9958c789)

- [x] Stage 3: First complete draft of the Self Assessment 
    - [x] Document technical specifications of the Fluentd project. 
        - [x] Self-assessment use
               commit: [fb01a71](https://github.com/Rana-KV/tag-security/commit/fb01a7161e612d49c7ada017c405a2108390384f)
        - [x] Security functions and features
                commit: [b376db8](https://github.com/Rana-KV/tag-security/commit/b376db8b88df450a1da1b535d8984072c6af49e4)
        - [x] Project compliance
               commit: [b376db8](https://github.com/Rana-KV/tag-security/commit/b376db8b88df450a1da1b535d8984072c6af49e4)
        - [x] Secure development practices
                commit: [b51ee1d](https://github.com/Rana-KV/tag-security/commit/b51ee1d9d8c514d59003c5bd4e2c0ff2221ef851)
        - [x] Security issue resolution
                commit: [5ba298b](https://github.com/Rana-KV/tag-security/commit/5ba298b22cb98bbb393ff4bc4d3972dfdbe03abf)
        - [x] Appendix
                commit: [3307698](https://github.com/Rana-KV/tag-security/commit/330769812b31db2df6fb88bfb3e70e893c651b2a)
    - [x]  Complete the security self assessment draft.

- [x] Stage 4: Iteration with the project
   - [x] Initiate discussion with Fluentd project maintainers.
   - [x]  Incorporate inputs and feedback from Fluentd project maintainers.
   - [x]  Document the findings.

- [x] Stage 5: Finalization
   - [x] Initiate PR
   - [x] Get feedback and findings from reviewers
   - [x] Fix the findings
   - [x] Merge the PR
   - [x] Close the issue
