### ISSUE TITLE
[Security Self-Assessment] Volcano

### ISSUE THREAD

**Issue by mayank-ramnani** [Rana-KV/tag-security#13]
## Details
Project Name: Volcano
Github URL: https://github.com/volcano-sh/volcano
CNCF project stage and issue (NA if not applicable): [Incubation](https://github.com/cncf/toc/blob/fbc846a3ac3f58ee9fe25d722cc64f0bf15bd86c/docs/PROJECTS.csv#L50)
- [Incubation Proposal](https://github.com/cncf/toc/blob/fbc846a3ac3f58ee9fe25d722cc64f0bf15bd86c/proposals/incubation/volcano.adoc)

Security Provider: No
Self Assessment Link (before PR): [Volcano Self Assessment](https://github.com/mayank-ramnani/tag-security/blob/main/assessments/projects/volcano/self-assessment.md)

## Tasks
- [x] Stage 1: Preparation
   - [x] Create a GitHub issue for the security self assessment of Volcano project.
      - [x] Issue Link in CNCF Tag-Security: https://github.com/Rana-KV/tag-security/issues/13
   - [x] Create a place holder of security self assessment.
      - [x] Create a fork of the CNCF Tag-Security in your Github.
      - [x] Create a new folder for the Volcano project.
      - [x] Add the security self assessment template under the project folder.
      - [x] Issue link of Initial Commit: https://github.com/mayank-ramnani/tag-security/commit/2fb69be4e0e53cbc1bb5139b2970f1cc8675c912
   - [x] Review Documentation of the Volcano project.
- [x]  Stage 2: Understand the Project Landscape
   - [x] Understand the overall project at a sufficient level of detail.
   - [x] Update overview section
      - [x] **Background** <br> commit: https://github.com/mayank-ramnani/tag-security/commit/b6f73acd2c1994501c85e6c98003808f0118f78c
      - [x] **Actors** <br> commit: https://github.com/mayank-ramnani/tag-security/commit/b6f73acd2c1994501c85e6c98003808f0118f78c
      - [x] **Actions** <br> commit: https://github.com/mayank-ramnani/tag-security/commit/b6f73acd2c1994501c85e6c98003808f0118f78c
      - [x] **Goals** <br> commit: https://github.com/mayank-ramnani/tag-security/commit/b6f73acd2c1994501c85e6c98003808f0118f78c
      - [x] **Non-Goals** <br> commit: https://github.com/mayank-ramnani/tag-security/commit/b6f73acd2c1994501c85e6c98003808f0118f78c
- [x]  Stage 3: First complete draft of the Self Assessment
   - [x] Document technical specifications of the Volcano project.
      - [x] **Self assessment use** <br> commit: https://github.com/mayank-ramnani/tag-security/commit/b6f73acd2c1994501c85e6c98003808f0118f78c
      - [x] **Security functions and features** <br> commit: https://github.com/mayank-ramnani/tag-security/commit/b6f73acd2c1994501c85e6c98003808f0118f78c
      - [x] **Project compliance** <br> commit: https://github.com/mayank-ramnani/tag-security/commit/b6f73acd2c1994501c85e6c98003808f0118f78c
      - [x] **Secure development practices** <br> commit: https://github.com/mayank-ramnani/tag-security/commit/b6f73acd2c1994501c85e6c98003808f0118f78c
      - [x] **Security issue resolution** <br> commit: https://github.com/mayank-ramnani/tag-security/commit/b6f73acd2c1994501c85e6c98003808f0118f78c
      - [x] **Appendix** <br> commit: https://github.com/mayank-ramnani/tag-security/commit/b6f73acd2c1994501c85e6c98003808f0118f78c
   - [x] Complete the security self assessment draft.

- [x]  Stage 4: Iteration with the project
   - [x] Initiate discussion with Volcano project maintainers.
   - [x] Incorporate inputs and feedback from Volcano project maintainers.
   - [x] Document the findings.

- [x] Stage 5: Finalization
   - [x] Initiate PR
   - [x] Get feedback and findings from reviewers
   - [x] Fix the findings
   - [x] Merge the PR
   - [x] Close the issue
