### ISSUE TITLE
[Security Self-assessment] Containerd

### ISSUE THREAD

**Issue by Nate-Smithline** [Rana-KV/tag-security#14]
### Details
Project Name: Containerd
Github URL: https://github.com/containerd/containerd

CNCF project stage: <Sandbox preparing for Incubation / Incubation preparing for Graduation / Graduated>
- Sandbox Proposal: https://github.com/Rana-KV/tag-security/issues/14#issue-1993720659
- Incubation Proposal: <Github_issue_link>
- Graduation Proposal: <Github_issue_link>

Security Provider: <Yes / **No**>

Self-assessment link (before PR): [<project_name> Security Self-Assessment](<Forked_Github_Repo_link>)

### Tasks
- [x] Stage 1: Preparation
   - [x] Create a GitHub issue for the security self assessment of **Containerd** project.
      - [x] Issue Link in CNCF Tag-Security: https://github.com/Rana-KV/tag-security/issues/14
   - [x] Create a place holder of security self assessment.
      - [x] Create a fork of the CNCF Tag-Security in your Github.
      - [x] Create a new folder for the **Containerd** project.
      - [x] Add the security self assessment template under the project folder.
      - [x] Issue link of Initial Commit: 551dc2f1cc4aea1e3d5eec3df35df1a88de9a00a
   - [x] Review Documentation of the **Containerd** project.
- [x]  Stage 2: Understand the Project Landscape
   - [x] Understand the overall project at a sufficient level of detail.
   - [x] Update overview section
      - [x] **Background** <br> commit: 31c97d3aee68037b6c6a6ca77d0ded1f96664d2e
      - [x] **Actors** <br> commit: 31c97d3aee68037b6c6a6ca77d0ded1f96664d2e
      - [x] **Actions** <br> commit: 7648122124a5348203d19bc979d78a3be61c21d3
      - [x] **Goals** <br> commit: e5ce655ca9443223b2736e9a9172d99eb138921b
      - [x] **Non-Goals** <br> commit: e5ce655ca9443223b2736e9a9172d99eb138921b
- [ ]  Stage 3: First complete draft of the Self Assessment
   - [x] Document technical specifications of the **Containerd** project.
      - [x] **Self assessment use** <br> commit: cfee7d66e7ba92ae4e2992ace1014aaa46e7affc
      - [x] **Security functions and features** <br> commit: f5b3289b338957ae9a052c92d74a9de52c8a87d1
      - [x] **Project compliance** <br> commit: 251bc85715451d32d48f92d2e621bf63ce7b34ba
      - [x] **Secure development practices** <br> commit: e2ffe3e99d681f03c2f68f5c66c81b7b70981def
      - [x] **Security issue resolution** <br> commit: bda8c5400d310d77c91a8a9558bbcd7bf3fa3967
      - [x] **Appendix** <br> commit: 2ce0717532f38fcaf718d1c7cfd97364e0faf215
   - [ ] Complete the security self assessment draft.

- [ ]  Stage 4: Iteration with the project
   - [ ] Initiate discussion with <project_name> project maintainers.
   - [ ] Incorporate inputs and feedback from <project_name> project maintainers.
   - [ ] Document the findings.

- [ ] Stage 5: Finalization
   - [ ] Initiate PR
   - [ ] Get feedback and findings from reviewers
   - [ ] Fix the findings
   - [ ] Merge the PR
   - [ ] Close the issue
