### ISSUE TITLE
[Security Self Assessment] TiKV

### ISSUE THREAD

**Issue by Michael-Susu12138** [Rana-KV/tag-security#15]
Project Name: TiKV

Github URL: https://github.com/tikv/tikv

CNCF project stage and issue: Graduated

Security Provider: No 

Self-assessment repo: [TiKV Security Self Assessment](https://github.com/Michael-Susu12138/tag-security)

# Tasks

## Stage 1: Preparation

- [x] Create a GitHub issue for the [security self assessment of TiKV project](https://github.com/Rana-KV/tag-security/issues/15).
  - [x] Issue [Link](https://github.com/Michael-Susu12138/tag-security) in CNCF Tag-Security
- [x] Create a placeholder of security self assessment.
- [x] Create a fork of the CNCF Tag-Security in your Github.
  - [x] Create a new folder for the TiKV project.
  - [x] Add the security self assessment template under the project folder.
  - [x] Include link to our Github Fork: [commit_link](https://github.com/Rana-KV/tag-security/compare/main...Michael-Susu12138:tag-security:main)
  - [x] Include the link to our first commit `<5cdc948257febc4ea1c747ca8b14f6cd5e42be55>`

- [x] Review Documentation of the TiKV project.

## Stage 2: Understand the Project Landscape

- [x] Understand the overall project at a sufficient level of detail.
  - [x] Update overview section
    - [x] Background
      - commit: `<9c0ebf8ddd98e33c935ce94d54e9c7c8ce8fe8a7>`
    - [x] Actors
      - commit: `<d082b58e2aa370fde364f58b7fc9567dcc5725e5>`
    - [x] Actions
      - commit: `<d082b58e2aa370fde364f58b7fc9567dcc5725e5>`
    - [x] Goals
      - commit: `<bca534a1e39ff65ab081d57930e843d929defc1b>`
    - [x] Non-Goals
      - commit: `<bca534a1e39ff65ab081d57930e843d929defc1b>`

## Stage 3: First complete draft of the Self Assessment

- [x] Document technical specifications of the TiKV project.
  - [x] Self assessment use
    - commit: `<9c0ebf8ddd98e33c935ce94d54e9c7c8ce8fe8a7>`
  - [x] Security functions and features
    - commit: `<82b45b13c8c2b3c0df8ad9de4819ef99962567b2>`
  - [x] Project compliance
    - commit: `<1472861a081ce723e9ad9c97124e0830afdc02aa>`
  - [x] Secure development practices
    - commit: `<82b45b13c8c2b3c0df8ad9de4819ef99962567b2>`
  - [x] Security issue resolution
    - commit: `<ba3999267b19e69a5608db95def3647a1152de0a>`
  - [x] Appendix
    - commit: `<067bee71f92c793f6dd9b53c490b8fbd3a8fbf26>&&<0d181814eeb0e8916d71683cdd5b0dac1645b9ae>`

- [x] Complete the security self assessment draft. `<d25aa478fbfb84b79162ccaeac049b3aa3ee1274>`

## Stage 4: Iteration with the project

- [ ] Initiate discussion with TiKV project maintainers.
- [ ] Incorporate inputs and feedback from TiKV project maintainers.
- [ ] Document the findings.

## Stage 5: Finalization

- [ ] Initiate PR
- [ ] Get feedback and findings from reviewers
- [ ] Fix the findings
- [ ] Merge the PR
- [ ] Close the issue
