### ISSUE TITLE
[Security Self-Assessment] OpenMetrics

### ISSUE THREAD

**Issue by MutteTejeshu** [Rana-KV/tag-security#16]
### Details
Project Name: OpenMetrics

Github URL: https://github.com/OpenObservability/OpenMetrics

CNCF project stage: Incubation preparing for Graduation
- Sandbox Proposal: https://github.com/cncf/toc/blob/main/proposals/sandbox/openmetrics.adoc
- Incubation Proposal: https://github.com/cncf/toc/blob/main/proposals/incubation/incubation-openmetrics.md

Security Provider: No

Self-assessment link (before PR): [OpenMetrics Security Self-Assessment](https://github.com/kc34251/OpenMetrics/blob/main/assessments/projects/OpenMetrics/self-assessment.md)

### Tasks
- [x] Stage 1: Preparation
   - [x] Create a GitHub issue for the security self assessment of OpenMetrics project.
      - [x] Issue Link in CNCF Tag-Security: https://github.com/Rana-KV/tag-security/issues/16
   - [x] Create a place holder of security self assessment.
      - [x] Create a fork of the CNCF Tag-Security in your Github.
      - [x] Create a new folder for the OpenMetrics project.
      - [x] Add the security self assessment template under the project folder.
      - [x] Issue link of Initial Commit: https://github.com/kc34251/OpenMetrics/commit/633ad404361a9e375892a6f213862145a174069b
   - [x] Review Documentation of the OpenMetrics project.
- [x]  Stage 2: Understand the Project Landscape
   - [x] Understand the overall project at a sufficient level of detail.
   - [x] Update overview section
      - [x] **Background** <br> commit: https://github.com/kc34251/OpenMetrics/commit/404c93afe7b056da07ba8ab9ea624b7c4decb8c8
      - [x] **Actors** <br> commit: https://github.com/kc34251/OpenMetrics/commit/fa0e520669c1c2ce44ed09599c9eceedecf565aa
      - [x] **Actions** <br> commit: https://github.com/kc34251/OpenMetrics/commit/b98ee0f23032f82ccd0ee683ddf48272624db96d
      - [x] **Goals** <br> commit: https://github.com/kc34251/OpenMetrics/commit/7acc00d3ec3787ac06f0edf4a4df89ac79e4723a
      - [x] **Non-Goals** <br> commit: https://github.com/kc34251/OpenMetrics/commit/fa0e520669c1c2ce44ed09599c9eceedecf565aa
- [x]  Stage 3: First complete draft of the Self Assessment
   - [x] Document technical specifications of the <project_name> project.
      - [x] **Self assessment use** <br> commit: https://github.com/kc34251/OpenMetrics/commit/79eee437be821fb6d4cdf414c80d399e3d2ba780
      - [x] **Security functions and features** <br> commit: https://github.com/kc34251/OpenMetrics/commit/f8bf1c3391f565faed064bba3d621fffcc918f4d
      - [x] **Project compliance** <br> commit: https://github.com/kc34251/OpenMetrics/commit/fa0e520669c1c2ce44ed09599c9eceedecf565aa
      - [x] **Secure development practices** <br> commit: https://github.com/kc34251/OpenMetrics/commit/53f14ad0b31dd1a2a1e1d835612196367a9825b9
      - [x] **Security issue resolution** <br> commit: https://github.com/kc34251/OpenMetrics/commit/be655927d6f7a1690adaee8538467913d748b161
      - [x] **Appendix** <br> commit: https://github.com/kc34251/OpenMetrics/commit/2d01e1061003b6b9083a18f0d6ecc2b36a29bea2
   - [x] Complete the security self assessment draft.

- [x]  Stage 4: Iteration with the project
   - [x] Initiate discussion with <project_name> project maintainers.
   - [x] Incorporate inputs and feedback from <project_name> project maintainers.
   - [x] Document the findings.

- [ ] Stage 5: Finalization
   - [ ] Initiate PR
   - [ ] Get feedback and findings from reviewers
   - [ ] Fix the findings
   - [ ] Merge the PR
   - [ ] Close the issue
