### ISSUE TITLE
[Security Self-Assessment] CoreDNS

### ISSUE THREAD

**Issue by TomY-Zhang** [Rana-KV/tag-security#17]
### Details
Project Name: CoreDNS

Github URL: https://github.com/coredns/coredns

CNCF project stage: Graduated
- Graduation Proposal: https://github.com/kubernetes/enhancements/blob/master/keps/sig-network/427-coredns/README.md

Security Provider: No

Self-assessment link (before PR): [CoreDNS Security Self-Assessment](https://github.com/TomY-Zhang/tag-security/blob/main/assessments/projects/coredns/self-assessment.md)

### Tasks
- [x] Stage 1: Preparation
   - [x] Create a GitHub issue for the security self assessment of CoreDNS project.
      - [x] Issue Link in CNCF Tag-Security: https://github.com/Rana-KV/tag-security/issues/17
   - [x] Create a place holder of security self assessment.
      - [x] Create a fork of the CNCF Tag-Security in your Github.
      - [x] Create a new folder for the CoreDNS project.
      - [x] Add the security self assessment template under the project folder.
      - [x] Issue link of Initial Commit: https://github.com/TomY-Zhang/tag-security/commit/aa0f6e86c6e188c50ed9159d7310423f036120bc
   - [x] Review Documentation of the CoreDNS project.
- [x]  Stage 2: Understand the Project Landscape
   - [x] Understand the overall project at a sufficient level of detail.
   - [x] Update overview section
      - [x] **Background** <br> commit: [Vamshi](https://github.com/TomY-Zhang/tag-security/commit/07acdc1747f7c82fd8f00f2e19d18fe88a39435e)
      - [x] **Actors** <br> commit: [Tom](https://github.com/TomY-Zhang/tag-security/commit/c28a16d5a10bc19ae2917b6a1fbead36031e597d)
      - [x] **Actions** <br> commit: [Rohit](https://github.com/TomY-Zhang/tag-security/commit/f1e8bb1dd392b0e80b1141568b84a8a910d2c278)
      - [x] **Goals** <br> commit: [Maryam](https://github.com/TomY-Zhang/tag-security/commit/f4661529dadf90710f9e423e5a326470ae806045)
      - [x] **Non-Goals** <br> commit: [Maryam](https://github.com/TomY-Zhang/tag-security/commit/f4661529dadf90710f9e423e5a326470ae806045)
- [x]  Stage 3: First complete draft of the Self Assessment
   - [x] Document technical specifications of the CoreDNS project.
      - [x] **Self assessment use** <br> commit: [Tom](https://github.com/TomY-Zhang/tag-security/commit/de7509c2a16e6466e1b796502b710e8f4fa1630b)
      - [x] **Security functions and features** <br> commit: [Tom](https://github.com/TomY-Zhang/tag-security/commit/ea59ffa9d4f7a4761624f7e7746583dd883aa282)
      - [x] **Project compliance** <br> commit: [Tom](https://github.com/TomY-Zhang/tag-security/commit/7e334e8bf78a477472eea3f8889dd9decc2c55c4)
      - [x] **Secure development practices** <br> commit: [Maryam](https://github.com/TomY-Zhang/tag-security/commit/1e84c61a4e28d98472fd3e907706a8fa710bfd6b)
      - [x] **Security issue resolution** <br> commit: [Rohit](https://github.com/TomY-Zhang/tag-security/commit/c2c72adba7fea0f39efec8de28a13adbe03b8cd2)
      - [x] **Appendix** <br> commit: [Vamshi](https://github.com/TomY-Zhang/tag-security/commit/c11956bd79c72ab4b4d2161985ae38ecd8d5f518)
   - [x] Complete the security self assessment draft.

- [x]  Stage 4: Iteration with the project
   - [x] Initiate discussion with CoreDNS project maintainers.
   - [x] Incorporate inputs and feedback from CoreDNS project maintainers.
   - [x] Document the findings.

- [ ] Stage 5: Finalization
   - [x] Initiate PR
   - [x] Get feedback and findings from reviewers
   - [x] Fix the findings
   - [ ] Merge the PR
   - [ ] Close the issue
