### ISSUE TITLE
[Security Self-Assessment] External Secrets Operator

### ISSUE THREAD

**Issue by rrgodhorus** [Rana-KV/tag-security#19]
### Details

Project Name: External Secrets Operator

Github URL: https://github.com/external-secrets/external-secrets

CNCF project stage: [sandbox](https://github.com/cncf/toc/blob/fbc846a3ac3f58ee9fe25d722cc64f0bf15bd86c/docs/PROJECTS.csv#L141)
- Sandbox Proposal: https://github.com/cncf/sandbox/issues/211

Security Provider: No

Self-assessment link (before PR): [External Secrets Operator Security Self-Assessment](https://github.com/rrgodhorus/tag-security/blob/main/assessments/projects/external-secrets/self-assessment.md)

### Tasks
- [x] Stage 1: Preparation
   - [x] Create a GitHub issue for the security self assessment of External Secrets Operator project.
      - [x] Issue Link in CNCF Tag-Security: https://github.com/Rana-KV/tag-security/issues/19
   - [x] Create a place holder of security self assessment.
      - [x] Create a fork of the CNCF Tag-Security in your Github.
      - [x] Create a new folder for the External Secrets Operator project.
      - [x] Add the security self assessment template under the project folder.
      - [x] Issue link of Initial Commit: https://github.com/rrgodhorus/tag-security/commit/5ddf520a53afaa11f4a6392142440d2b44bc31aa
   - [x] Review Documentation of the External Secrets Operator project.
- [x]  Stage 2: Understand the Project Landscape
   - [x] Understand the overall project at a sufficient level of detail.
   - [x] Update overview section
      - [x] **Background** <br> commit: https://github.com/rrgodhorus/tag-security/commit/c3b7470bef4b8976211d961a1c5ca66c48ab0da6
      - [x] **Actors** <br> commit: https://github.com/rrgodhorus/tag-security/commit/c3b7470bef4b8976211d961a1c5ca66c48ab0da6
      - [x] **Actions** <br> commit: https://github.com/rrgodhorus/tag-security/commit/c3b7470bef4b8976211d961a1c5ca66c48ab0da6
      - [x] **Goals** <br> commit: https://github.com/rrgodhorus/tag-security/commit/c3b7470bef4b8976211d961a1c5ca66c48ab0da6
      - [x] **Non-Goals** <br> commit: https://github.com/rrgodhorus/tag-security/commit/c3b7470bef4b8976211d961a1c5ca66c48ab0da6
- [x]  Stage 3: First complete draft of the Self Assessment
   - [x] Document technical specifications of the External Secrets Operator project.
      - [x] **Self assessment use** <br> commit: https://github.com/rrgodhorus/tag-security/commit/c3b7470bef4b8976211d961a1c5ca66c48ab0da6
      - [x] **Security functions and features** <br> commit: https://github.com/rrgodhorus/tag-security/commit/5d107d3d0f141b6454dfa1f7b0d273f523e2ef83
      - [x] **Project compliance** <br> commit: https://github.com/rrgodhorus/tag-security/commit/c3b7470bef4b8976211d961a1c5ca66c48ab0da6
      - [x] **Secure development practices** <br> commit: https://github.com/rrgodhorus/tag-security/commit/c3b7470bef4b8976211d961a1c5ca66c48ab0da6
      - [x] **Security issue resolution** <br> commit: https://github.com/rrgodhorus/tag-security/commit/c3b7470bef4b8976211d961a1c5ca66c48ab0da6
      - [x] **Appendix** <br> commit: https://github.com/rrgodhorus/tag-security/commit/c3b7470bef4b8976211d961a1c5ca66c48ab0da6
   - [x] Complete the security self assessment draft.

- [x]  Stage 4: Iteration with the project
   - [x] Initiate discussion with External Secrets Operator project maintainers.
   - [x] Incorporate inputs and feedback from External Secrets Operator project maintainers.
   - [x] Document the findings.

- [ ] Stage 5: Finalization
   - [x] Initiate PR
   - [x] Get feedback and findings from reviewers
   - [x] Fix the findings
   - [ ] Merge the PR
   - [ ] Close the issue
