### ISSUE TITLE
[Security Self-Assessment] Antrea

### ISSUE THREAD

**Issue by molofgarb** [Rana-KV/tag-security#2]
### Details
Project Name: Antrea

Github URL: https://github.com/antrea-io/antrea

CNCF project stage: Sandbox preparing for Incubation
- Sandbox Proposal: https://github.com/cncf/sandbox/issues/243

Security Provider: No

Self-assessment link (before PR): [Antrea Security Self-Assessment](https://github.com/molofgarb/tag-security-11/blob/main/assessments/projects/antrea/self-assessment.md)

### Tasks
- [x] Stage 1: Preparation
   - [x] Create a GitHub issue for the security self assessment of Antrea project.
      - [x] Issue Link in CNCF Tag-Security: https://github.com/Rana-KV/tag-security/issues/2
   - [x] Create a place holder of security self assessment.
      - [x] Create a fork of the CNCF Tag-Security in your Github.
      - [x] Create a new folder for the Antrea project.
      - [x] Add the security self assessment template under the project folder.
      - [x] Issue link of Initial Commit: https://github.com/molofgarb/tag-security-11/commit/9b5394fadadf3dc9a0112af1bbb803bb6be4331d
   - [x] Review Documentation of the Antrea project.
- [x]  Stage 2: Understand the Project Landscape
   - [x] Understand the overall project at a sufficient level of detail.
   - [x] Update overview section
      - [x] **Background** <br> commit: https://github.com/molofgarb/tag-security-11/commit/aa9ed37b776d01886fa699d7bc2188aabb7a3392
      - [x] **Actors** <br> commit: https://github.com/molofgarb/tag-security-11/commit/d5d811e66eebb7adda7c19771c749410161096d8
      - [x] **Actions** <br> commit: https://github.com/molofgarb/tag-security-11/commit/aa9ed37b776d01886fa699d7bc2188aabb7a3392
      - [x] **Goals** <br> commit: https://github.com/molofgarb/tag-security-11/commit/d5d811e66eebb7adda7c19771c749410161096d8
      - [x] **Non-Goals** <br> commit: https://github.com/molofgarb/tag-security-11/commit/aa9ed37b776d01886fa699d7bc2188aabb7a3392
- [x]  Stage 3: First complete draft of the Self Assessment
   - [x] Document technical specifications of the Antrea project.
      - [x] **Self assessment use** <br> commit: https://github.com/molofgarb/tag-security-11/commit/093b78b6004f8be95978cf395479d77421026baf
      - [x] **Security functions and features** <br> commit: https://github.com/molofgarb/tag-security-11/commit/b9355e9dd787023d1856b16b91a9d76c11071249
      - [x] **Project compliance** <br> commit: https://github.com/molofgarb/tag-security-11/commit/d5d811e66eebb7adda7c19771c749410161096d8
      - [x] **Secure development practices** <br> commit: https://github.com/molofgarb/tag-security-11/commit/9d44fb78345097d9d9b665ff2ffbae28725999e8
      - [x] **Security issue resolution** <br> commit: https://github.com/molofgarb/tag-security-11/commit/9d44fb78345097d9d9b665ff2ffbae28725999e8
      - [x] **Appendix** <br> commit: https://github.com/molofgarb/tag-security-11/commit/0467f845cca162c4e036fbf62533c2349eeff448
   - [x] Complete the security self assessment draft.

- [x]  Stage 4: Iteration with the project
   - [x] Initiate discussion with Antrea project maintainers.
   - [x] Incorporate inputs and feedback from Antrea project maintainers.
   - [x] Document the findings.

- [ ] Stage 5: Finalization
   - [x] Initiate PR
   - [ ] Get feedback and findings from reviewers
   - [ ] Fix the findings
   - [ ] Merge the PR
   - [ ] Close the issue
