### ISSUE TITLE
[Security Self-Assessment] CloudEvents

### ISSUE THREAD

**Issue by Igor8mr** [Rana-KV/tag-security#20]
### Details
Project Name: CloudEvents

Github URL: [CloudEvents](https://github.com/cloudevents/spec)

CNCF project stage: Incubating
- Sandbox Proposal: [CloudEvents Sandbox Proposal](https://github.com/cncf/toc/blob/fbc846a3ac3f58ee9fe25d722cc64f0bf15bd86c/proposals/sandbox/cloudevents.md)
- Incubation Proposal: [CloudEvents Incubation Proposal](https://github.com/cncf/toc/blob/fbc846a3ac3f58ee9fe25d722cc64f0bf15bd86c/reviews/incubation/incubation-cloudevents.md)
- Graduation Proposal: N/A
 
Security Provider: No

Self-assessment link (before PR): [CloudEvents Security Self-Assessment](<https://github.com/Igor8mr/tag-security/blob/main/assessments/projects/cloud-events/self-assessment.md>)

### Tasks
- [x] Stage 1: Preparation
   - [x] Create a GitHub issue for the security self assessment of CloudEvents project.
      - [x] Issue Link in CNCF Tag-Security: [[Security Self-Assessment] CloudEvents #20](https://github.com/Rana-KV/tag-security/issues/20)
   - [x] Create a place holder of security self assessment.
      - [x] Create a fork of the CNCF Tag-Security in your Github.
      - [x] Create a new folder for the CloudEvents project.
      - [x] Add the security self assessment template under the project folder.
      - [x] Issue link of Initial Commit: [Initial Commit](https://github.com/cncf/tag-security/commit/dbb64c61742a802fad8f54c2ea387505f2e6bc7d)
   - [x] Review Documentation of the CloudEvents project.
- [x]  Stage 2: Understand the Project Landscape
   - [x] Understand the overall project at a sufficient level of detail.
   - [x] Update overview section
      - [x] **Background** <br> commit: <https://github.com/cncf/tag-security/commit/52f05dc7866c713c4fd144201c5c6e06ab1a8c4f>
      - [x] **Actors** <br> commit: <https://github.com/cncf/tag-security/commit/588ae438f74457cd87358853a28bcb87e3ed3dfd>
      - [x] **Actions** <br> commit: <https://github.com/cncf/tag-security/commit/30b4cc0be4318be2abfb4d96c23c1a8faea6f4c2>
      - [x] **Goals** <br> commit: <https://github.com/cncf/tag-security/commit/01f3efbace5139cb18bbee15b1f24b3fa32ae60d>
      - [x] **Non-Goals** <br> commit: <https://github.com/cncf/tag-security/commit/01f3efbace5139cb18bbee15b1f24b3fa32ae60d>
- [x]  Stage 3: First complete draft of the Self Assessment
   - [x] Document technical specifications of the CloudEvents project.
      - [x] **Self assessment use** <br> commit: <https://github.com/cncf/tag-security/commit/e76789de06ba50f07de87642bcb22d88d0fd3086>
      - [x] **Security functions and features** <br> commit: <https://github.com/cncf/tag-security/commit/3e63fac0431d055a02a0f758e61f1d72a0b6633f>
      - [x] **Project compliance** <br> commit: <https://github.com/Igor8mr/tag-security/commit/bbd641c3dff4b9eb120c465136370d5aa72c29fb>
      - [x] **Secure development practices** <br> commit: <https://github.com/cncf/tag-security/commit/0461979cdcd9fc03b380dde38a169ad7c06ad726>
      - [x] **Security issue resolution** <br> commit: <https://github.com/cncf/tag-security/commit/958f6e81383b90423c7616a3b66f730544625acf>
      - [x] **Appendix** <br> commit: <https://github.com/cncf/tag-security/commit/e9eab852404a575d57f12633ef4f7e1fa420daa0>
   - [x] Complete the security self assessment draft.

- [x]  Stage 4: Iteration with the project
   - [x] Initiate discussion with CloudEvents project maintainers.
   - [x] Incorporate inputs and feedback from CloudEvents project maintainers.
   - [x] Document the findings.

- [x] Stage 5: Finalization
   - [x] Initiate PR
   - [x] Get feedback and findings from reviewers
   - [x] Fix the findings
   - [ ] Merge the PR
   - [ ] Close the issue
