### ISSUE TITLE
[Security Self-Assessment] Linkerd

### ISSUE THREAD

**Issue by amanda-gonzalez** [Rana-KV/tag-security#21]
### **Details**
Project Name: Linkerd

Github URL: https://github.com/linkerd

CNCF project stage: Graduated

Sandbox Proposal: [Linkerd Sandbox Proposal](https://github.com/cncf/toc/blob/fbc846a3ac3f58ee9fe25d722cc64f0bf15bd86c/proposals/sandbox/linkerd.adoc)
Incubation Proposal: [Linkerd Incubation Proposal](https://github.com/cncf/toc/blob/fbc846a3ac3f58ee9fe25d722cc64f0bf15bd86c/reviews/incubation/incubation-linkerd.md)
Graduation Proposal: [Linkerd Graduation Proposal](https://github.com/cncf/toc/blob/fbc846a3ac3f58ee9fe25d722cc64f0bf15bd86c/proposals/graduation/linkerd.md)
Security Provider: <Yes / No>

Self-assessment link (before PR): [Linkerd Security Self-Assessment](https://github.com/amanda-gonzalez/tag-security/tree/ffa5cc55031fe8f44615f0d227956914cf5e16eb/assessments/projects/linkerd)

### **Tasks**

- [x] Stage 1: Preparation
    - [x] Create a GitHub issue for the security self assessment of CloudEvents project.
        - [x] Issue Link in CNCF Tag-Security: https://github.com/Rana-KV/tag-security/issues/21)
    - [x] Create a place holder of security self assessment.
        - [x] Create a fork of the CNCF Tag-Security in your Github.
        - [x] Create a new folder for the CloudEvents project.
        - [x] Add the security self assessment template under the project folder. 
        - [x] Issue link of [Initial Commit](amanda-gonzalez@ffa5cc5): amanda-gonzalez@ffa5cc5
    - [x] Review Documentation of the CloudEvents project.
 
- [x] Stage 2: Understand the Project Landscape
    - [x] Understand the overall project at a sufficient level of detail.
    - [x] Update overview section
        - [x]  Background
        commit: amanda-gonzalez@7e2c310
        - [x] Actors
        commit: amanda-gonzalez@7e2c310
        - [x] Actions
       commit: amanda-gonzalez@7e2c310
        - [x] Goals
        commit: amanda-gonzalez@7e2c310
        - [x] Non-Goals
        commit: amanda-gonzalez@7e2c310

- [x] Stage 3: First complete draft of the Self Assessment
    - [x] Document technical specifications of the CloudEvents project.
        - [x] Self assessment use
        commit: amanda-gonzalez@0f8ceaa
        - [x] Security functions and features
        commit: amanda-gonzalez@806abb7
        - [x] Project compliance
        commit: amanda-gonzalez@bae30ca
        - [x] Secure development practices
        commit: amanda-gonzalez@c4b47fe
        - [x] Security issue resolution
        commit: amanda-gonzalez@2f53d5e
        - [x] Appendix
        commit: amanda-gonzalez@2f53d5e
    - [x] Complete the security self assessment draft.

- [x] Stage 4: Iteration with the project
    - [x] Initiate discussion with CloudEvents project maintainers.
    - [ ] Incorporate inputs and feedback from CloudEvents project maintainers.
    - [x] Document the findings.
 

- [x] Stage 5: Finalization
    - [x] Initiate PR
    - [x] Get feedback and findings from reviewers
    - [x] Fix the findings
    - [ ] Merge the PR
    - [ ] Close the issue
