### ISSUE TITLE
[Security Review] knative

### ISSUE THREAD

**Issue by Jabberwockiii** [Rana-KV/tag-security#22]
### Details
Project Name: Knative

Github URL: https://github.com/knative

CNCF project stage: Incubation preparing for Graduation
- Incubation Proposal: https://github.com/cncf/sandbox/issues/218 (Specifically, this issue addressed the onboarding of Knative into CNCF when it was already an incubating project)

Security Provider: No

Self-assessment link (before PR): [Knative Security Self-Assessment](https://github.com/Jabberwockiii/tag-security-knative-12/blob/main/assessments/projects/knative/self-assessment.md)

### Tasks
- [x] Stage 1: Preparation
    - [x] Create a GitHub issue for the security self assessment of Knative project.
        - [x] Issue Link in Rana-KV Tag-Security: https://github.com/Rana-KV/tag-security/issues/22
        - [ ] Issue Link in CNCF Tag-Security: NOT YET APPLICABLE
    - [x] Create a place holder of security self assessment.
        - [x] Create a fork of the CNCF Tag-Security in your Github.
        - [x] Create a new folder for the Knative project.
        - [x] Add the security self assessment template under the project folder.
        - [x] Issue link of Initial Commit: https://github.com/Rana-KV/tag-security/commit/99e03078cf2f743b8e9b78590c0140d195d09ba3
    - [x] Review Documentation of the Knative project.
- [x]  Stage 2: Understand the Project Landscape
    - [x] Understand the overall project at a sufficient level of detail.
    - [x] Update overview section
        - [x] **Background**
        - [x] **Actors**
        - [x] **Actions**
        - [x] **Goals**
        - [x] **Non-Goals**
- [x]  Stage 3: First complete draft of the Self Assessment
    - [x] Document technical specifications of the Knative project.
        - [x] **Self assessment use**
        - [x] **Security functions and features**
        - [x] **Project compliance**
        - [x] **Secure development practices**
        - [x] **Security issue resolution**
        - [x] **Appendix**
    - [x] Complete the security self assessment draft. https://github.com/Jabberwockiii/tag-security-knative-12/commit/25b6d177ee45e7da3bf452e3fe6869d259a6041f

- [ ]  Stage 4: Iteration with the project
    - [ ] Initiate discussion with Knative project maintainers.
    - [ ] Incorporate inputs and feedback from Knative project maintainers.
    - [ ] Document the findings.

- [ ] Stage 5: Finalization
    - [ ] Initiate PR
    - [ ] Get feedback and findings from reviewers
    - [ ] Fix the findings
    - [ ] Merge the PR
    - [ ] Close the issue
