### ISSUE TITLE
[Security Self-Assessment] etcd

### ISSUE THREAD

**Issue by qianxichen233** [Rana-KV/tag-security#23]
### Details
Project Name: etcd

Github URL: [etcd](https://github.com/etcd-io/etcd)

CNCF project stage: Graduated
- Sandbox Proposal: N/A
- Incubation Proposal: [Incubation Proposal](https://github.com/cncf/toc/blob/fbc846a3ac3f58ee9fe25d722cc64f0bf15bd86c/proposals/incubation/etcd.adoc)
- Graduation Proposal: [Graduation Proposal](https://github.com/cncf/toc/blob/fbc846a3ac3f58ee9fe25d722cc64f0bf15bd86c/proposals/graduation/etcd.md)

Security Provider: No

Self-assessment link (before PR): [etcd Security Self-Assessment](https://github.com/qianxichen233/tag-security/blob/main/assessments/projects/etcd/self-assessment.md)

### Tasks
- [x] Stage 1: Preparation
   - [x] Create a GitHub issue for the security self assessment of etcd project.
      - [x] Issue Link in CNCF Tag-Security: [https://github.com/Rana-KV/tag-security/issues/23](https://github.com/Rana-KV/tag-security/issues/23)
   - [x] Create a place holder of security self assessment.
      - [x] Create a fork of the CNCF Tag-Security in your Github.
      - [x] Create a new folder for the etcd project.
      - [x] Add the security self assessment template under the project folder.
      - [x] Issue link of Initial Commit: [Initial Commit](https://github.com/qianxichen233/tag-security/commit/389bb71f38139745840ab76b625626b391ba8f82)
   - [x] Review Documentation of the etcd project.
- [x]  Stage 2: Understand the Project Landscape
   - [x] Understand the overall project at a sufficient level of detail.
   - [x] Update overview section
      - [x] **Background** <br> commit: [\<fa33d21>](https://github.com/qianxichen233/tag-security/commit/fa33d21ae3bf7313ab5d1917620bd9544b051ca4)
      - [x] **Actors** <br> commit: [<6f24218>](https://github.com/qianxichen233/tag-security/commit/6f242185ea67a7890eb99552b7d26ebd38d9f926)
      - [x] **Actions** <br> commit: [<6f24218>](https://github.com/qianxichen233/tag-security/commit/6f242185ea67a7890eb99552b7d26ebd38d9f926)
      - [x] **Goals** <br> commit: [<6f24218>](https://github.com/qianxichen233/tag-security/commit/6f242185ea67a7890eb99552b7d26ebd38d9f926)
      - [x] **Non-Goals** <br> commit: [<6f24218>](https://github.com/qianxichen233/tag-security/commit/6f242185ea67a7890eb99552b7d26ebd38d9f926)
- [x]  Stage 3: First complete draft of the Self Assessment
   - [x] Document technical specifications of the etcd project.
      - [x] **Self assessment use** <br> commit: [<6f24218>](https://github.com/qianxichen233/tag-security/commit/6f242185ea67a7890eb99552b7d26ebd38d9f926)
      - [x] **Security functions and features** <br> commit: [<6f24218>](https://github.com/qianxichen233/tag-security/commit/6f242185ea67a7890eb99552b7d26ebd38d9f926)
      - [x] **Project compliance** <br> commit: [<00a484c>](https://github.com/qianxichen233/tag-security/commit/00a484c1f2ed0efa73b61b2bdb652b9a89cf7126)
      - [x] **Secure development practices** <br> commit: [<33cfeb0>](https://github.com/qianxichen233/tag-security/commit/33cfeb0335ad07012deee9f9223ecf252b16ee9c)
      - [x] **Security issue resolution** <br> commit: [<3edbb18>](https://github.com/qianxichen233/tag-security/commit/3edbb1805e81c2de9c1fc671a572a46f103b695f)
      - [x] **Appendix** <br> commit: [<3276b32>](https://github.com/qianxichen233/tag-security/commit/3276b3238cd2d6243225b8d7f190f8a21aa330ff)
   - [x] Complete the security self assessment draft.

- [x]  Stage 4: Iteration with the project
   - [x] Initiate discussion with etcd project maintainers.
   - [x] Incorporate inputs and feedback from etcd project maintainers.
   - [x] Document the findings.

- [ ] Stage 5: Finalization
   - [x] Initiate PR
   - [x] Get feedback and findings from reviewers
   - [x] Fix the findings
   - [ ] Merge the PR
   - [ ] Close the issue
