### ISSUE TITLE
[Security Self-Assessment] OpenTelemetry

### ISSUE THREAD

**Issue by PrathamGupta** [Rana-KV/tag-security#24]
## Details
Project Name: OpenTelemetry
Github URL: https://github.com/open-telemetry/opentelemetry.io
CNCF project stage and issue (NA if not applicable): [Incubation](https://github.com/cncf/toc/blob/fbc846a3ac3f58ee9fe25d722cc64f0bf15bd86c/docs/PROJECTS.csv#L36)
- [Incubation Proposal](https://github.com/cncf/toc/blob/fbc846a3ac3f58ee9fe25d722cc64f0bf15bd86c/proposals/sandbox/opentelemetry.adoc)

Security Provider: No
Self Assessment Link (before PR): [OpenTelemetry Self Assessment](https://github.com/PrathamGupta/tag-security/blob/b10856cde1d3c58dde6b805c165e04ddee676158/assessments/projects/open-telemetry/self-assessment.md)

## Tasks
- [x] Stage 1: Preparation
   - [x] Create a GitHub issue for the security self assessment of OpenTelemetry project.
      - [x] Issue Link in CNCF Tag-Security: https://github.com/Rana-KV/tag-security/issues/24
   - [x] Create a place holder of security self assessment.
      - [x] Create a fork of the CNCF Tag-Security in your Github.
      - [x] Create a new folder for the OpenTelemetry project.
      - [x] Add the security self assessment template under the project folder.
      - [x] Issue link of Initial Commit: 3352f89
   - [x] Review Documentation of the OpenTelemetry project.
- [x]  Stage 2: Understand the Project Landscape
   - [x] Understand the overall project at a sufficient level of detail.
   - [x] Update overview section
      - [x] **Background** <br> commit: 9343a25
      - [x] **Actors** <br> commit: 9343a25
      - [x] **Actions** <br> commit: 38f714a
      - [x] **Goals** <br> commit: d83441d 00fccf2
      - [x] **Non-Goals** <br> commit: d83441d 00fccf2 
- [x]  Stage 3: First complete draft of the Self Assessment
   - [x] Document technical specifications of the OpenTelemetry project.
      - [x] **Self assessment use** <br> commit: c0063f9
      - [x] **Security functions and features** <br> commit: 6e67fd9
      - [x] **Project compliance** <br> commit: Not Applicable
      - [x] **Secure development practices** <br> commit: 6e08a8c ccc5715
      - [x] **Security issue resolution** <br> commit: 2de2039
      - [x] **Appendix** <br> commit: db40911 
   - [x] Complete the security self assessment draft.

- [x]  Stage 4: Iteration with the project
   - [x] Initiate discussion with OpenTelemetry project maintainers.
   - [x] Incorporate inputs and feedback from OpenTelemetry project maintainers.
   - [x] Document the findings.

- [ ] Stage 5: Finalization
   - [x] Initiate PR
   - [x] Get feedback and findings from reviewers
   - [x] Fix the findings
   - [ ] Merge the PR
   - [ ] Close the issue
