### ISSUE TITLE
[Security Review] OpenFGA

### ISSUE THREAD

**Issue by AM-git-hub** [Rana-KV/tag-security#25]
### Details
Project Name: OpenFGA

Github URL: https://github.com/openfga/openfga

CNCF project stage: Sandbox
- Sandbox Proposal: <Github_issue_link>

Security Provider: Yes

Self-assessment link (before PR): https://github.com/AM-git-hub/tag-security/blob/main/assessments/projects/openfga/self-assessment.md

### Tasks
- [x] Stage 1: Preparation
   - [x] Create a GitHub issue for the security self assessment of <project_name> project.
      - [x] Issue Link in CNCF Tag-Security: https://github.com/Rana-KV/tag-security/issues/25
   - [x] Create a place holder of security self assessment.
      - [x] Create a fork of the CNCF Tag-Security in your Github.
      - [x] Create a new folder for the OpenFGA project.
      - [x] Add the security self assessment template under the project folder.
      - [x] Issue link of Initial Commit: https://github.com/AM-git-hub/tag-security/commit/c68dfd1e9725c10c1cec000b062cd530e4288f58
   - [x] Review Documentation of the OpenFGA project.
- [x]  Stage 2: Understand the Project Landscape
   - [x] Understand the overall project at a sufficient level of detail.
   - [x] Update overview section
      - [x] **Background** <br> commit: https://github.com/AM-git-hub/tag-security/commit/12c5325ea51be9a4a9dde4ad3f81486837a74d9c
      - [x] **Actors** <br> commit: https://github.com/AM-git-hub/tag-security/commit/8db32b28500d1878f3947352900b61acd5862e22
      - [x] **Actions** <br> commit: https://github.com/AM-git-hub/tag-security/commit/af580e4135382dd0ed55fbf2bfccbededc80bdab
      - [x] **Goals** <br> commit: https://github.com/AM-git-hub/tag-security/commit/34d4cd2259531c81cf5af0255d3dc7262acb25d2
      - [x] **Non-Goals** <br> commit: https://github.com/AM-git-hub/tag-security/commit/0785b49e6aae4ee5d5c670d75514697db84cdd9c
- [x]  Stage 3: First complete draft of the Self Assessment
   - [x] Document technical specifications of the OpenFGA project.
      - [x] **Self assessment use** <br> commit: https://github.com/AM-git-hub/tag-security/commit/651c04344d0ce4e4b337df49c3a26fe91ff85e3d
      - [x] **Security functions and features** <br> commit: https://github.com/AM-git-hub/tag-security/commit/6ea622677291db344ef79bc30157fa904b44a126
      - [x] **Project compliance** <br> commit: https://github.com/AM-git-hub/tag-security/commit/70c770c7cd61f7f69f0d46948ebd34a4a0207bbf
      - [x] **Secure development practices** <br> commit: https://github.com/AM-git-hub/tag-security/commit/1c8a4e6446a2c0e4effd663979bddd47b7701e22
      - [x] **Security issue resolution** <br> commit: https://github.com/AM-git-hub/tag-security/commit/33ae5fab330e2cdff9101aee6bb765c5b6d6c66a
      - [x] **Appendix** <br> commit: https://github.com/AM-git-hub/tag-security/commit/c75b56e9c94feaacd2b8e2d63f5ba7cf50ce6ba0
   - [x] Complete the security self assessment draft.

- [x]  Stage 4: Iteration with the project
   - [x] Initiate discussion with OpenFGA project maintainers.
   - [x] Incorporate inputs and feedback from OpenFGA project maintainers.
   - [x] Document the findings.

- [ ] Stage 5: Finalization
   - [x] Initiate PR
   - [ ] Get feedback and findings from reviewers
   - [ ] Fix the findings
   - [ ] Merge the PR
   - [ ] Close the issue
