### ISSUE TITLE
[Security Self-assessment] emissary-ingress/emissary

### ISSUE THREAD

**Issue by yashaswi2000** [Rana-KV/tag-security#3]
### Details
Project Name: emissary-ingress/emissary

Github URL: [emissary](https://github.com/emissary-ingress/emissary)

CNCF project stage: Incubation preparing for Graduation
- Incubation Proposal: https://github.com/cncf/toc/pull/435

Security Provider: No

Self-assessment link (before PR): [self-assessment](https://github.com/yashaswi2000/tag-security/blob/main/assessments/projects/emissary-ingress/emissary-ingress-security-self-assessment.md)

### Tasks
- [x] Stage 1: Preparation
   - [x] Create a GitHub issue for the security self assessment of emissary-ingress/emissary project.
      - [x] Issue Link in CNCF Tag-Security: https://github.com/Rana-KV/tag-security/issues/3
   - [x] Create a place holder of security self assessment.
      - [x] Create a fork of the CNCF Tag-Security in your Github.
      - [x] Create a new folder for the emissary-ingress/emissary project.
      - [x] Add the security self assessment template under the project folder.
      - [x] Issue link of Initial Commit: https://github.com/yashaswi2000/tag-security/commit/a51772f3a9a9b7c2f74b180869f1b7a2c2320942
   - [x] Review Documentation of the emissary-ingress/emissary project.
- [x]  Stage 2: Understand the Project Landscape
   - [x] Understand the overall project at a sufficient level of detail.
   - [x] Update overview section
      - [x] **Background** <br> commit: https://github.com/yashaswi2000/tag-security/commit/33b99d14688a331753d3fad4fcf02fa01160f3bd
      - [x] **Actors** <br> commit: https://github.com/yashaswi2000/tag-security/commit/972e2dc15bf4615a122b477f7587f0fa13ad5139
      - [x] **Actions** <br> commit:  https://github.com/yashaswi2000/tag-security/commit/4269559d0df4f935a9c4a6d640ff23f114bc8069
      - [x] **Goals** <br> commit: https://github.com/yashaswi2000/tag-security/commit/1b277ba8e3fcdc2d0b41332acc9fc9623c4f0caf
      - [x] **Non-Goals** <br> commit: https://github.com/yashaswi2000/tag-security/commit/1b277ba8e3fcdc2d0b41332acc9fc9623c4f0caf
- [x]  Stage 3: First complete draft of the Self Assessment
   - [x] Document technical specifications of the emissary-ingress/emissary project.
      - [x] **Self assessment use** <br> commit: https://github.com/yashaswi2000/tag-security/commit/38110f6b0077e19661d95a8da978b5aa7f17afc2
      - [x] **Security functions and features** <br> commit: https://github.com/yashaswi2000/tag-security/commit/aade45e1edde035b4198ed86c03b650a86874c7a
      - [x] **Project compliance** <br> commit: https://github.com/yashaswi2000/tag-security/commit/8ac3e11a79f4a3fa3cd7bf14185dcecbe3e553b3
      - [x] **Secure development practices** <br> commit: https://github.com/yashaswi2000/tag-security/commit/5a1744571990b8d9f6f84a285a3c1da4ff7d6868
      - [x] **Security issue resolution** <br> commit: https://github.com/yashaswi2000/tag-security/commit/c9fc1fc6cbaa29441e7c5b9da509742dc4c4a7ba
      - [x] **Appendix** <br> commit: https://github.com/yashaswi2000/tag-security/commit/8ac3e11a79f4a3fa3cd7bf14185dcecbe3e553b3
   - [x] Complete the security self assessment draft.

- [ ]  Stage 4: Iteration with the project
   - [ ] Initiate discussion with emissary-ingress/emissary project maintainers.
   - [ ] Incorporate inputs and feedback from emissary-ingress/emissary project maintainers.
   - [ ] Document the findings.

- [ ] Stage 5: Finalization
   - [ ] Initiate PR
   - [ ] Get feedback and findings from reviewers
   - [ ] Fix the findings
   - [ ] Merge the PR
   - [ ] Close the issue
