### ISSUE TITLE
[Security Self-Assessment] OpenKruise

### ISSUE THREAD

**Issue by bradcush** [Rana-KV/tag-security#4]
### Details
Project Name: OpenKruise

Github URL: https://github.com/openkruise/kruise

CNCF project stage: [Sandbox preparing for Incubation](https://github.com/cncf/toc/blob/fbc846a3ac3f58ee9fe25d722cc64f0bf15bd86c/docs/PROJECTS.csv#L78)
- Sandbox Proposal: https://github.com/cncf/sandbox/issues/264 
- Incubation Proposal: [OpenKruise proposal for CNCF Incubation](https://github.com/cncf/toc/blob/fbc846a3ac3f58ee9fe25d722cc64f0bf15bd86c/proposals/incubation/openkruise.md#openkruise-proposal-for-cncf-incubation)

Security Provider: No

Self-assessment link (before PR): [OpenKruise Security Self-assessment](https://github.com/bradcush/tag-security/blob/openkruise-assessment/assessments/projects/openkruise/self-assessment.md)

### Tasks
- [x] Stage 1: Preparation
   - [x] Create a GitHub issue for the security self assessment of OpenKruise project.
      - [x] Issue Link in CNCF Tag-Security: https://github.com/Rana-KV/tag-security/issues/4
   - [x] Create a place holder of security self assessment.
      - [x] Create a fork of the CNCF Tag-Security in your Github.
      - [x] Create a new folder for the OpenKruise project.
      - [x] Add the security self assessment template under the project folder.
      - [x] Issue link of Initial Commit: https://github.com/cncf/tag-security/commit/2a8bc4f338ba51d9828b310dcd1bec2286cb0f48
   - [x] Review Documentation of the OpenKruise project.
- [x]  Stage 2: Understand the Project Landscape
   - [x] Understand the overall project at a sufficient level of detail.
   - [x] Update overview section
      - [x] **Background** <br> commit: https://github.com/cncf/tag-security/commit/d628aec18705101d53d4ba15a02a0dc208a4d764
      - [x] **Actors** <br> commit: https://github.com/cncf/tag-security/commit/d628aec18705101d53d4ba15a02a0dc208a4d764
      - [x] **Actions** <br> commit: https://github.com/cncf/tag-security/commit/d628aec18705101d53d4ba15a02a0dc208a4d764
      - [x] **Goals** <br> commit: https://github.com/cncf/tag-security/commit/d628aec18705101d53d4ba15a02a0dc208a4d764
      - [x] **Non-Goals** <br> commit: https://github.com/cncf/tag-security/commit/d628aec18705101d53d4ba15a02a0dc208a4d764
- [x]  Stage 3: First complete draft of the Self Assessment
   - [x] Document technical specifications of the OpenKruise project.
      - [x] **Self assessment use** <br> commit: https://github.com/cncf/tag-security/commit/e4e33769dd9e3b8d66692a6a89497379ede81f8d
      - [x] **Security functions and features** <br> commit: https://github.com/cncf/tag-security/commit/d3bdc4db91e1d20d623e8539878b8e4a66e6639e
      - [x] **Project compliance** <br> commit: https://github.com/cncf/tag-security/commit/4925dc997daa34922a68f2c9b26c34cb9680131a
      - [x] **Secure development practices** <br> commit: https://github.com/cncf/tag-security/commit/221e2ee59dd7bfd79fa00dea9d40390cceb22983
      - [x] **Security issue resolution** <br> commit: https://github.com/cncf/tag-security/commit/6d9c9fc63c7d0b166883c36493188718747bdc09
      - [x] **Appendix** <br> commit: https://github.com/cncf/tag-security/commit/3dd85cfb8a0d26e4485c66e1731e201c5d254e37
   - [x] Complete the security self assessment draft.

- [x]  Stage 4: Iteration with the project
   - [x] Initiate discussion with OpenKruise project maintainers.
   - [x] Incorporate inputs and feedback from OpenKruise project maintainers.
   - [x] Document the findings.

- [x] Stage 5: Finalization
   - [x] Initiate PR
   - [x] Get feedback and findings from reviewers
   - [x] Fix the findings
   - [x] Merge the PR
   - [x] Close the issue
