### ISSUE TITLE
[Security Self-Assessment] Cortex

### ISSUE THREAD

**Issue by heydc7** [Rana-KV/tag-security#5]
### Details
Project Name: Cortex

Github URL: https://github.com/cortexproject/cortex

CNCF project stage: Incubation preparing for Graduation
- Sandbox Proposal: https://github.com/cncf/toc/issues/108
- Incubation Proposal: https://github.com/cncf/toc/pull/315

Security Provider: No

Self-assessment link (before PR): [Cortex Security Self-Assessment](https://github.com/heydc7/tag-security/blob/main/assessments/projects/cortex/self-assessment.md)

### Tasks
- [X] Stage 1: Preparation
   - [X] Create a GitHub issue for the security self assessment of Cortex project.
      - [X] Issue Link in CNCF Tag-Security: https://github.com/Rana-KV/tag-security/issues/5
   - [X] Create a place holder of security self assessment.
      - [X] Create a fork of the CNCF Tag-Security in your Github.
      - [X] Create a new folder for the <project_name> project.
      - [X] Add the security self assessment template under the project folder.
      - [X] Issue link of Initial Commit: https://github.com/heydc7/tag-security/commit/cd8bbd2f41fe1a199a0d95faad3e192966adf065
   - [X] Review Documentation of the Cortex project.
- [X]  Stage 2: Understand the Project Landscape
   - [X] Understand the overall project at a sufficient level of detail.
   - [X] Update overview section
      - [X] **Background** <br> commit: https://github.com/heydc7/tag-security/commit/cb67881e97643831e6081f464481ae3f5da09ae3
      - [X] **Actors** <br> commit: https://github.com/heydc7/tag-security/commit/cb67881e97643831e6081f464481ae3f5da09ae3
      - [X] **Actions** <br> commit: https://github.com/heydc7/tag-security/commit/cb67881e97643831e6081f464481ae3f5da09ae3
      - [X] **Goals** <br> commit: https://github.com/heydc7/tag-security/commit/cb67881e97643831e6081f464481ae3f5da09ae3
      - [X] **Non-Goals** <br> commit: https://github.com/heydc7/tag-security/commit/cb67881e97643831e6081f464481ae3f5da09ae3
- [X]  Stage 3: First complete draft of the Self Assessment
   - [X] Document technical specifications of the Cortex project.
      - [X] **Self assessment use** <br> commit: https://github.com/heydc7/tag-security/commit/cb67881e97643831e6081f464481ae3f5da09ae3
      - [X] **Security functions and features** <br> commit: https://github.com/heydc7/tag-security/commit/cb67881e97643831e6081f464481ae3f5da09ae3
      - [X] **Project compliance** <br> commit: https://github.com/heydc7/tag-security/commit/cb67881e97643831e6081f464481ae3f5da09ae3
      - [X] **Secure development practices** <br> commit: https://github.com/heydc7/tag-security/commit/cb67881e97643831e6081f464481ae3f5da09ae3
      - [X] **Security issue resolution** <br> commit: https://github.com/heydc7/tag-security/commit/cb67881e97643831e6081f464481ae3f5da09ae3
      - [X] **Appendix** <br> commit: https://github.com/heydc7/tag-security/commit/cb67881e97643831e6081f464481ae3f5da09ae3
   - [X] Complete the security self assessment draft.

- [X]  Stage 4: Iteration with the project
   - [X] Initiate discussion with Cortex project maintainers.
   - [x] Incorporate inputs and feedback from Cortex project maintainers.
   - [x] Document the findings.

- [ ] Stage 5: Finalization
   - [x] Initiate PR
   - [x] Get feedback and findings from reviewers
   - [x] Fix the findings
   - [ ] Merge the PR
   - [ ] Close the issue
