### ISSUE TITLE
[Security Self-assessment] Rook

### ISSUE THREAD

**Issue by dhauss** [Rana-KV/tag-security#6]
### Details
Project Name: Rook

Github URL: [Rook Repo](https://github.com/rook/rook)

CNCF project stage: Graduated
- Sandbox Proposal: [Rook Sandbox Proposal](https://github.com/cncf/toc/blob/fbc846a3ac3f58ee9fe25d722cc64f0bf15bd86c/proposals/sandbox/rook.adoc)
- Incubation Proposal: [Rook Incubation Proposal](https://github.com/cncf/toc/blob/fbc846a3ac3f58ee9fe25d722cc64f0bf15bd86c/reviews/incubation/incubation-rook.md)
- Graduation Proposal: [Rook Graduation Proposal](https://github.com/cncf/toc/blob/fbc846a3ac3f58ee9fe25d722cc64f0bf15bd86c/reviews/graduation/graduation-rook.md)

Security Provider: No

Self-assessment link (before PR): [Rook Security Self-Assessment](https://github.com/dhauss/tag-security)

### Tasks
- [x] Stage 1: Preparation
   - [x] Create a GitHub issue for the security self assessment of Rook project.
      - [x] Issue Link in CNCF Tag-Security: [Rook Issue Link](https://github.com/Rana-KV/tag-security/issues/6)
   - [x] Create a place holder of security self assessment.
      - [x] Create a fork of the CNCF Tag-Security in your Github.
      - [x] Create a new folder for the Rook project.
      - [x] Add the security self assessment template under the project folder.
      - [x] Issue link of Initial Commit: [72678c2](https://github.com/Rana-KV/tag-security/commit/72678c2f72d3c6a57154ff418e3e80ec9dbae186)
   - [x] Review Documentation of the Rook project.
- [x]  Stage 2: Understand the Project Landscape
   - [x] Understand the overall project at a sufficient level of detail.
   - [x] Update overview section
      - [x] **Background** <br> commit: [6a1af2c](https://github.com/dhauss/tag-security/commit/6a1af2c56adce575c616a056464902586e27b8a9)
      - [x] **Actors** <br> commit: [be44210](https://github.com/dhauss/tag-security/commit/be442103b24dd57854caafc6ce612cb724e3a0c3)
      - [x] **Actions** <br> commit: [10c1aa1](https://github.com/dhauss/tag-security/commit/10c1aa1808fea34a52639362170246ccd10fb83f)
      - [x] **Goals** <br> commit: [3ec16cb](https://github.com/dhauss/tag-security/commit/3ec16cb7498f4639f56830ce6b609f4de44060f6)
      - [x] **Non-Goals** <br> commit: [936f48d](https://github.com/dhauss/tag-security/commit/936f48d59de6b39722971fd0607b1b774d60ad88)
- [x]  Stage 3: First complete draft of the Self Assessment
   - [x] Document technical specifications of the Rook project.
      - [x] **Self assessment use** <br> commit: [c3a6e44](https://github.com/dhauss/tag-security/commit/c3a6e446d08ff72730460ff3539e443884d42f3f)
      - [x] **Security functions and features** <br> commit: [71e0202](https://github.com/dhauss/tag-security/commit/71e020299923c11e6062228ee0308c0a54cbf8b4)
      - [x] **Project compliance** <br> commit: [b1b55a6](https://github.com/dhauss/tag-security/commit/b1b55a6c3ce3e2898927107f452c925e7336b581)
      - [x] **Secure development practices** <br> commit: [7daebc5](https://github.com/dhauss/tag-security/commit/7daebc586bc3da99a8633f20aad2b5def914b8d8)
      - [x] **Security issue resolution** <br> commit: [a259537](https://github.com/dhauss/tag-security/commit/a2595379f21373ce90d483b914cc7aedddbf67d3)
      - [x] **Appendix** <br> commit: [2ca1d25](https://github.com/dhauss/tag-security/commit/2ca1d25c23d408f1093aca6fc05749e493e19139)
   - [x] Complete the security self assessment draft.

- [x]  Stage 4: Iteration with the project
   - [x] Initiate discussion with Rook project maintainers.
   - [x] Incorporate inputs and feedback from Rook project maintainers.
   - [x] Document the findings.

- [ ] Stage 5: Finalization
   - [x] Initiate PR
   - [ ] Get feedback and findings from reviewers
   - [ ] Fix the findings
   - [ ] Merge the PR
   - [ ] Close the issue
