### ISSUE TITLE
[Security Self Assessment] NATS

### ISSUE THREAD

**Issue by ddk304** [Rana-KV/tag-security#8]
### Details
Project Name: Nats.io

Github URL: https://github.com/nats-io/nats-server

CNCF project stage: < Incubation >
- Incubation Proposal: [Incubation Proposal](https://github.com/cncf/toc/blob/fbc846a3ac3f58ee9fe25d722cc64f0bf15bd86c/proposals/incubation/nats.adoc)

Security Provider: < No >

Self-assessment link (before PR): [<project_name> Security Self-Assessment](https://github.com/ddk304/tag-security/blob/main/assessments/projects/nats/self-assessment.md)

### Tasks
- [x] Stage 1: Preparation
   - [x] Create a GitHub issue for the security self assessment of <nats> project.
      - [x] Issue Link in CNCF Tag-Security: <link>
   - [x] Create a place holder of security self assessment.
      - [x] Create a fork of the CNCF Tag-Security in your Github.
      - [x] Create a new folder for the NATS project.
      - [x] Add the security self assessment template under the project folder.
      - [x] Issue link of Initial Commit: <link> c7ddf4b3ccfff515883a293eda86fcfe54458844
   - [x] Review Documentation of the NATS project.
- [x]  Stage 2: Understand the Project Landscape
   - [x] Understand the overall project at a sufficient level of detail.
   - [x] Update overview section
      - [x] **Background** <br> commit: <db9904832a4829edbc1b5f9dafa03d96d4802070>
      - [x] **Actors** <br> commit: <db9904832a4829edbc1b5f9dafa03d96d4802070>
      - [x] **Actions** <br> commit: <db9904832a4829edbc1b5f9dafa03d96d4802070>
      - [x] **Goals** <br> commit: <db9904832a4829edbc1b5f9dafa03d96d4802070>
      - [x] **Non-Goals** <br> commit: <db9904832a4829edbc1b5f9dafa03d96d4802070>
- [x]  Stage 3: First complete draft of the Self Assessment
   - [x] Document technical specifications of the NATS project.
      - [x] **Self assessment use** <br> commit: <db9904832a4829edbc1b5f9dafa03d96d4802070>
      - [x] **Security functions and features** <br> commit: <db9904832a4829edbc1b5f9dafa03d96d4802070>
      - [x] **Project compliance** <br> commit: <db9904832a4829edbc1b5f9dafa03d96d4802070>
      - [x] **Secure development practices** <br> commit: <db9904832a4829edbc1b5f9dafa03d96d4802070>
      - [x] **Security issue resolution** <br> commit: <db9904832a4829edbc1b5f9dafa03d96d4802070>
      - [x] **Appendix** <br> commit: <db9904832a4829edbc1b5f9dafa03d96d4802070>
   - [x] Complete the security self assessment draft.

- [ x]  Stage 4: Iteration with the project
   - [ x] Initiate discussion with NATS project maintainers.
   - [ x] Incorporate inputs and feedback from NATS project maintainers.
   - [x] Document the findings.

- [x] Stage 5: Finalization
   - [x] Initiate PR
   - [x] Get feedback and findings from reviewers
   - [x] Fix the findings
   - [ ] Merge the PR
   - [ ] Close the issue
